"""add thumbnails

Revision ID: 0f0bd025baa8
Revises: d37c506bc30e
Create Date: 2024-04-01 18:39:16.828538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0bd025baa8'
down_revision = 'd37c506bc30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_images_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_images_data')

    # ### end Alembic commands ###
