"""udpate main agents revert

Revision ID: 15dcdf833ba7
Revises: e5a3d5ec17af
Create Date: 2024-04-22 16:44:12.579516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dcdf833ba7'
down_revision = 'e5a3d5ec17af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_agent')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agents_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_images_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_images_data')
        batch_op.drop_column('images_data')
        batch_op.drop_column('agents_data')

    op.create_table('main_agent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='main_agent_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='main_agent_pkey')
    )
    # ### end Alembic commands ###