"""Add agents_data and images_data columns to User model

Revision ID: 7bf33abf57eb
Revises: a5dd9d9b0414
Create Date: 2024-03-18 22:57:30.955186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf33abf57eb'
down_revision = 'a5dd9d9b0414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_data', sa.JSON(), nullable=True))
        batch_op.drop_column('foldername')
        batch_op.drop_column('agents_file')
        batch_op.drop_column('result_count')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agents_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('images_data', sa.JSON(), nullable=True))
        batch_op.drop_constraint('user_folder_path_key', type_='unique')
        batch_op.drop_column('folder_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_path', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_folder_path_key', ['folder_path'])
        batch_op.drop_column('images_data')
        batch_op.drop_column('agents_data')

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('agents_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('foldername', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('survey_data')

    # ### end Alembic commands ###
