"""Add foldername to Survey

Revision ID: 7f3e9c2445bc
Revises: 295fd5d8f740
Create Date: 2024-03-14 08:58:17.405641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3e9c2445bc'
down_revision = '295fd5d8f740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foldername', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('foldername')

    # ### end Alembic commands ###
