"""Rename token_balance to credits

Revision ID: a09c7a3bcdc2
Revises: f4f9b17899f3
Create Date: 2024-03-19 20:05:56.268157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09c7a3bcdc2'
down_revision = 'f4f9b17899f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.drop_column('token_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_balance', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
