"""add class document

Revision ID: 00089260aadf
Revises: fea836fee979
Create Date: 2024-04-30 16:46:38.251968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00089260aadf'
down_revision = 'fea836fee979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('top_p')
        batch_op.drop_column('temperature')
        batch_op.drop_column('model')
        batch_op.drop_column('max_tokens')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_p', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.drop_table('document')
    # ### end Alembic commands ###
