"""add details to meeting for image and summary

Revision ID: 03445dca3b7a
Revises: d49275b1c72e
Create Date: 2024-04-24 03:55:37.737998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03445dca3b7a'
down_revision = 'd49275b1c72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_image_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_image_data')
        batch_op.drop_column('image_data')
        batch_op.drop_column('summary')
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###
