"""change timeframe summary variable names

Revision ID: 3363c59c7561
Revises: 00089260aadf
Create Date: 2024-05-01 04:37:11.364106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3363c59c7561'
down_revision = '00089260aadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.alter_column('agents_data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('images_data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('thumbnail_images_data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('agent_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('thumbnail_images_data',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('images_data',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('agents_data',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
