"""Add agents, questions, and answers columns to Meeting model

Revision ID: 7a9e65615ed5
Revises: 922be503132c
Create Date: 2024-03-22 18:06:09.158966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a9e65615ed5'
down_revision = '922be503132c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agents', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('questions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))
        batch_op.drop_column('meeting_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('answers')
        batch_op.drop_column('questions')
        batch_op.drop_column('agents')

    # ### end Alembic commands ###
