"""change timeframe model to base64 image storage

Revision ID: 908ab172ff07
Revises: e001fa446418
Create Date: 2024-05-02 16:28:35.101443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '908ab172ff07'
down_revision = 'e001fa446418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('thumbnail_image_data',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_image_data',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
        batch_op.alter_column('image_data',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
