"""summarize prepended to timeframe image data

Revision ID: cf0a014a0d51
Revises: 908ab172ff07
Create Date: 2024-05-03 05:51:37.419256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0a014a0d51'
down_revision = '908ab172ff07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_image_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_thumbnail_image_data', sa.Text(), nullable=True))
        batch_op.drop_column('image_data')
        batch_op.drop_column('thumbnail_image_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_image_data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('summary_thumbnail_image_data')
        batch_op.drop_column('summary_image_data')

    # ### end Alembic commands ###
