"""change models for thumbnails

Revision ID: db012ab9052e
Revises: 0f0bd025baa8
Create Date: 2024-04-02 17:04:43.273292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db012ab9052e'
down_revision = '0f0bd025baa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_images_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_images_data')
        batch_op.drop_column('images_data')

    # ### end Alembic commands ###
