"""Update Timeframe image data columns to LargeBinary

Revision ID: e001fa446418
Revises: 3363c59c7561
Create Date: 2024-05-01 07:01:27.011212

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e001fa446418'
down_revision = '3363c59c7561'
branch_labels = None
depends_on = None


def upgrade():
  with op.batch_alter_table('timeframe', schema=None) as batch_op:
    batch_op.alter_column('image_data',
                          existing_type=sa.Text(),
                          type_=sa.LargeBinary(),
                          existing_nullable=True,
                          postgresql_using='image_data::bytea')
    batch_op.alter_column('thumbnail_image_data',
                          existing_type=sa.Text(),
                          type_=sa.LargeBinary(),
                          existing_nullable=True,
                          postgresql_using='thumbnail_image_data::bytea')


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('timeframe', schema=None) as batch_op:
    batch_op.alter_column('thumbnail_image_data',
                          existing_type=sa.LargeBinary(),
                          type_=sa.TEXT(),
                          existing_nullable=True)
    batch_op.alter_column('image_data',
                          existing_type=sa.LargeBinary(),
                          type_=sa.TEXT(),
                          existing_nullable=True)

  # ### end Alembic commands ###
