"""update timeframes with summaries and imges v2

Revision ID: e0a703ef3a65
Revises: 03445dca3b7a
Create Date: 2024-04-24 20:08:51.791131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a703ef3a65'
down_revision = '03445dca3b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_image_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeframe', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_image_data')
        batch_op.drop_column('image_data')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
