"""Add custom entries to Agent model

Revision ID: fea836fee979
Revises: bac681d72589
Create Date: 2024-04-26 08:31:33.922657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea836fee979'
down_revision = 'bac681d72589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('top_p', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('top_p')
        batch_op.drop_column('temperature')
        batch_op.drop_column('max_tokens')

    # ### end Alembic commands ###
